### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Lennoard/DDGUI#2]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Lennoard** [comment]
Thank you. While I can't make it right now, it should get addressed eventually.

**Comment by mondlicht-und-sterne** [comment]
and if not - it was also only information - because no screenshot is displayed, therefore aquch my issue.

then the issue could also be closed.
